### PR TITLE
Added visible check

### PR DESCRIPTION
**Pull request by riviello444**
the visible check works really smooth, if the aim is locked it will stop when the enemy will be invisible even if ur still holding the button

i also changed the settings in futures.cpp and made rcs more random bc i didnt like it but yk u can bring it back i just removed the multiple configs

### CODE REVIEW

**Comment by ekknod** [comment]
Your commit is breaking:
- configuration system design
- aimbot design
- rcs design
- triggerbot design

**Comment by ekknod** [comment]
Your commit is breaking:
- configuration system design
- aimbot design
- rcs design
- triggerbot design

**Comment by riviello444** [comment]
> Your commit is breaking:
> 
> * configuration system design
> * aimbot design
> * rcs design
> * triggerbot design

just implement the visible offset and the check in the aimbot section as i mentioned its ur source do what u want i cant imagine playing with aimbot that targets thru walls :D i

**Comment by GitZurah** [comment]
@riviello444 please reconsider how you made this pull request and re-make the vischeck so that it can easily be merged without conflicts - i think everyone would enjoy a working vischeck but in the current state you provided it it breaks basically the entire source

**Pull request closed without merging**
